name: Deploy ง่ายๆ

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  deploy-job:
    runs-on: ubuntu-latest
    steps:
      # 1. เช็คโค้ด
      - uses: actions/checkout@v4

      # 2. Login GHCR
      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3. เตรียมชื่อ repo เป็นตัวเล็ก
      - name: Lowercase Repo
        run: echo "REPO_LOWER=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      # 4. Build & Push Image
      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.REPO_LOWER }}:latest

      # 5. ส่งไฟล์ docker-compose ไป Server
      - name: Copy file
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 6864  # เช็คด้วยนะครับว่าพอร์ต SSH คือ 6864 จริงไหม (ถ้าปกติคือ 22)
          source: "docker-compose.yml"
          target: "/srv/api"

      # 6. สั่งรันบน Server
      - name: Run Docker
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 6864
          script: |
            cd /home/dserver/share_folder/application/fastapi/api-project
            # กำหนดชื่อ Image ให้ตรงกับที่ Build มา
            export GITHUB_REPOSITORY="${{ github.repository }}"
            export REPO_LOWER="${GITHUB_REPOSITORY,,}"
            
            # ดึง Image ล่าสุดมา
            docker compose pull
            # รันใหม่ (จะใช้ .env ที่เราสร้างไว้ใน Server เอง)
            docker compose up -d
            # ลบ Image เก่าทิ้ง
            docker image prune -f
