name: Deploy ง่ายๆ

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  deploy-job:
    runs-on: ubuntu-latest
    steps:
      # 1. เช็คโค้ด
      - uses: actions/checkout@v4

      # 2. Login GHCR
      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3. เตรียมชื่อ repo เป็นตัวเล็ก
      - name: Lowercase Repo
        run: echo "REPO_LOWER=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      # 4. Build & Push Image
      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true          
          tags: ghcr.io/${{ env.REPO_LOWER }}:latest
          no-cache: true

      # 5. ส่งไฟล์ docker-compose ไป Server
      - name: Copy file
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 6864
          source: "docker-compose.yml"
          # -------------------------------------------------------
          # ⚠️ แก้ตรงนี้ครับ: ต้องส่งไปที่ใหม่ ให้ตรงกับข้างล่าง
          # -------------------------------------------------------
          target: "/home/dserver/share_folder/application/fastapi/api-project"

      # 6. สั่งรันบน Server
      - name: Run Docker
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 6864
          script: |
            # -------------------------------------------------------
            # ✅ ตรงนี้ถูกต้องแล้วครับ cd เข้าไปที่ใหม่
            # -------------------------------------------------------
            cd /home/dserver/share_folder/application/fastapi/api-project
            
            # กำหนดชื่อ Image 
            export GITHUB_REPOSITORY="${{ github.repository }}"
            export REPO_LOWER="${GITHUB_REPOSITORY,,}"
            
            # ดึง Image ล่าสุดมา
            docker compose pull
            # รันใหม่ 
            docker compose up -d --force-recreate --remove-orphans
            # ลบ Image เก่าทิ้ง
            docker image prune -f
